#%RAML 1.0
title: Accounts API

/accounts:
  get:
    displayName: Get All Accounts
    description: Retrieve a list of all customer accounts.

    headers:
      Requester-ID:
        displayName: Requester-ID
        description: IDThe person or system requesting the data
        type: 
        required: true

    queryParameters:
      type:
        displayName: 
        description: 
        required: false
        type: string
        enum:
          - personal
          - business
      name:
        displayName: 
        description: 
        required: false
        type: string

  post:
    

      