#%RAML 1.0
title: Accounts API

types:
  Account: !include data-types/Account.raml

/accounts:
  get:
    displayName: Get All Accounts
    description: Retrieve a list of all customer accounts.

    headers:
      Requester-ID:
        displayName: Requester-ID
        description: ID of the person or system requesting the data
        type: string
        required: true
        default: R-ID-001

    queryParameters:
      type:
        displayName: Account type
        description: Type of account (Personal or Business)
        required: false
        type: string
        enum:
          - personal
          - business
      name:
        displayName: Owner's Name
        description: Name of the account owner
        required: false
        type: string
    responses:
      

  post:
    

      