#%RAML 1.0
title: Accounts API

/accounts:
  get:
    displayName: Get All Accounts
    description: Retrieve a list of all customer accounts.

    headers:
      Requester-ID:
        displayName: Requester-ID
        description: 
        

  post:
    

      