#%RAML 1.0 NamedExample

value:
-
  name: "Tom Jakson"
  type: "personal"
  address: "12345 GreenSt,Boulder,Colorado,82433,USA"
  airMiles: 600
-
  name: "Amna Mirta"
  type: "business"
  address: "12335 GreenSt,Boulder,Colorado,82533,USA"
  airMiles: 500